trigger:
- main
- feature/*

pool: AvneshPool

stages:
- stage: Terraformtodo
  displayName: Terraformtodo
  jobs:
  - job: terraforminit_plan
    displayName: Terraform Init & Plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'AvneshS'
        backendAzureRmStorageAccountName: 'avneshst'
        backendAzureRmContainerName: 'avneshct'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'AvneshS'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'AvneshS'

    
